# 数据库地址
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tom
    password: Dicy1101.
    url: jdbc:mysql://8.131.79.117:3306/dicy?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/dicy?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true


# tomcat接口地址访问地址
server:
  port: 8081


# 连接到webSocket 连接地址
wechatBot:
  url: ws://localhost:5555


# 微信消息处理地址(将消息发送给指定接口)
wechatBotServer:
  # 远程处理微信消息接口
  url: https://localhost
  # 是否开启远程处理微信消息功能
  isOpen: false


# 日志配置
logging:
  level:
    root: error
    io.uouo: error
    org.springframework: warn

